# Generated by Django 3.1.7 on 2021-03-03 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_auto_20210303_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='sex',
            field=models.CharField(default=0, max_length=1000),
        ),
    ]
