# Generated by Django 3.1.7 on 2021-03-29 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0007_profileavatars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileavatars',
            name='image',
        ),
        migrations.AddField(
            model_name='profileavatars',
            name='avatar',
            field=models.ImageField(default=0, upload_to='images'),
        ),
        migrations.AddField(
            model_name='profileavatars',
            name='background',
            field=models.ImageField(default=0, upload_to='images'),
        ),
    ]
