# Generated by Django 3.1.7 on 2021-05-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0013_profileaddinfo_telegram_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesFromLessons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=0, upload_to='gallery')),
                ('lesson_num', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.CharField(default=0, max_length=600)),
                ('text2', models.CharField(default=0, max_length=600)),
                ('lesson_num', models.IntegerField(default=0)),
            ],
        ),
    ]
