# Generated by Django 3.1.7 on 2021-05-23 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0014_imagesfromlessons_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='header',
            field=models.CharField(default=0, max_length=300),
        ),
    ]
