# Generated by Django 3.1.7 on 2021-05-26 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0015_lesson_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileaddinfo',
            name='is_teacher',
            field=models.IntegerField(default=0),
        ),
    ]
