# Generated by Django 3.1.7 on 2021-05-29 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('first', '0016_profileaddinfo_is_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='image1',
            field=models.ImageField(default=0, upload_to='gallery'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='image2',
            field=models.ImageField(default=0, upload_to='gallery'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='image3',
            field=models.ImageField(default=0, upload_to='gallery'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='image4',
            field=models.ImageField(default=0, upload_to='gallery'),
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homework', models.FileField(default=0, upload_to='gallery')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
