# Generated by Django 3.1.7 on 2021-05-30 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0017_auto_20210529_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='lesson_num',
            field=models.IntegerField(default=0),
        ),
    ]
