# Generated by Django 3.1.7 on 2021-05-30 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0018_homework_lesson_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesFromHomeworks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homework', models.FileField(default=0, upload_to='gallery')),
                ('homework_num', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='homework',
            name='homework',
        ),
        migrations.AddField(
            model_name='homework',
            name='comment',
            field=models.CharField(default=0, max_length=600),
        ),
        migrations.AddField(
            model_name='homework',
            name='homework_status',
            field=models.IntegerField(default=0),
        ),
    ]
