# Generated by Django 3.1.7 on 2021-05-30 03:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('first', '0021_auto_20210530_0553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagesfromhomeworks',
            old_name='homework_num',
            new_name='lesson_num',
        ),
        migrations.AddField(
            model_name='imagesfromhomeworks',
            name='times',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='imagesfromhomeworks',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='homework',
            name='comment',
            field=models.CharField(default='', max_length=600),
        ),
    ]
