# Generated by Django 3.1.7 on 2021-05-30 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0022_auto_20210530_0637'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='webinar_url',
            field=models.CharField(default=0, max_length=600),
        ),
        migrations.AddField(
            model_name='lesson',
            name='youtube_url',
            field=models.CharField(default=0, max_length=600),
        ),
    ]
