# Generated by Django 3.1.7 on 2021-05-30 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0025_homework_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='date',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='date',
        ),
    ]
