# Generated by Django 3.1.7 on 2021-05-30 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0026_auto_20210530_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='text1',
            field=models.CharField(default=0, max_length=6000),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='text2',
            field=models.CharField(default=0, max_length=6000),
        ),
    ]
