# Generated by Django 3.1.7 on 2021-07-24 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0027_auto_20210530_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagesfromhomeworks',
            name='created_at',
            field=models.IntegerField(default=0),
        ),
    ]
