# Generated by Django 3.1.7 on 2021-08-07 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('first', '0029_profileaddinfo_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='homework_status',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='lecture_status',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='lesson_num',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='task_title',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='user',
        ),
        migrations.AddField(
            model_name='courses',
            name='course_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='courses',
            name='places',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='courses',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='courses',
            name='title',
            field=models.CharField(default=0, max_length=600),
        ),
        migrations.CreateModel(
            name='SignedUpForCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_num', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='first.courses')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LessonInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(default=0, max_length=300)),
                ('lesson_num', models.IntegerField(default=0)),
                ('lecture_status', models.IntegerField(default=0)),
                ('homework_status', models.IntegerField(default=0)),
                ('course_num', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='first.courses')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
