# Generated by Django 3.1.7 on 2021-08-11 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0030_auto_20210807_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default=0, max_length=300)),
                ('type', models.CharField(default=0, max_length=100)),
                ('amount', models.IntegerField(default=0)),
                ('expires', models.IntegerField(default=0)),
            ],
        ),
    ]
