# Generated by Django 3.1.7 on 2021-09-09 14:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0033_auto_20210909_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='sum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='was',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
