# Generated by Django 3.1.7 on 2021-09-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0034_auto_20210909_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='link',
            field=models.CharField(default=0, max_length=300),
        ),
    ]
