# Generated by Django 3.1.7 on 2021-09-09 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0035_transactions_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='sum',
            new_name='payment_amount',
        ),
    ]
