# Generated by Django 3.1.7 on 2021-09-09 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0037_auto_20210909_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='was',
            field=models.DateField(default='09-09-2021'),
        ),
    ]
