# Generated by Django 3.1.7 on 2021-09-09 15:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0038_auto_20210909_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='was',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
