# Generated by Django 3.1.7 on 2021-09-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0042_auto_20210911_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='was',
            field=models.DateField(default='11/09/2021'),
        ),
    ]
