# Generated by Django 3.1.7 on 2021-09-14 11:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('first', '0043_auto_20210911_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileaddinfo',
            name='invited_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_inv', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profileaddinfo',
            name='is_invited',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='promo',
            name='expires',
            field=models.DateField(default=datetime.date(2021, 9, 15)),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='was',
            field=models.DateField(default='14/09/2021'),
        ),
    ]
