# Generated by Django 3.1.7 on 2021-09-14 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0044_auto_20210914_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileaddinfo',
            name='invited_count',
            field=models.IntegerField(default=0),
        ),
    ]
