# Generated by Django 3.1.7 on 2021-09-14 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0045_profileaddinfo_invited_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='after_transaction',
            field=models.IntegerField(default=0),
        ),
    ]
