# Generated by Django 3.1.7 on 2021-09-19 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0048_auto_20210919_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='times_can_use',
            field=models.IntegerField(default=1),
        ),
    ]
