# Generated by Django 3.1.7 on 2021-09-22 21:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0049_promo_times_can_use'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='expires',
            field=models.DateField(default=datetime.date(2021, 9, 24)),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='was',
            field=models.DateField(default='23/09/2021'),
        ),
    ]
