# Generated by Django 3.1.7 on 2021-09-25 10:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0050_auto_20210923_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileaddinfo',
            name='group_num',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='promo',
            name='expires',
            field=models.DateField(default=datetime.date(2021, 9, 26)),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='was',
            field=models.DateField(default='25/09/2021'),
        ),
    ]
