# Generated by Django 3.1.7 on 2021-09-29 13:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0051_auto_20210925_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='signedupforcourse',
            name='group_num',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='promo',
            name='expires',
            field=models.DateField(default=datetime.date(2021, 9, 30)),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='was',
            field=models.DateField(default='29/09/2021'),
        ),
    ]
