# Generated by Django 3.1.7 on 2021-10-01 20:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0053_lesson_course_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='expires',
            field=models.DateField(default=datetime.date(2021, 10, 2)),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='payment_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='was',
            field=models.DateField(default='01/10/2021'),
        ),
    ]
