# Generated by Django 3.1.7 on 2021-10-01 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0054_auto_20211001_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileaddinfo',
            name='wallet',
            field=models.FloatField(default=0),
        ),
    ]
