# Generated by Django 3.1.7 on 2021-10-05 18:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0055_auto_20211001_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='expires',
            field=models.DateField(default=datetime.date(2021, 10, 6)),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='after_transaction',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='was',
            field=models.DateField(default='05/10/2021'),
        ),
    ]
