# Generated by Django 3.1.7 on 2021-11-08 19:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0059_remove_imagesfromhomeworks_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileaddinfo',
            name='payment_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='promo',
            name='expires',
            field=models.DateField(default=datetime.date(2021, 11, 9)),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='was',
            field=models.DateField(default='08/11/2021'),
        ),
    ]
