# Generated by Django 3.1.7 on 2021-11-13 20:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0060_auto_20211108_2202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='text2',
            new_name='homework_text',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='text1',
        ),
        migrations.AlterField(
            model_name='promo',
            name='expires',
            field=models.DateField(default=datetime.date(2021, 11, 14)),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='was',
            field=models.DateField(default='13/11/2021'),
        ),
    ]
