# Generated by Django 3.1.7 on 2021-11-14 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0062_auto_20211114_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_status',
            field=models.IntegerField(default=0),
        ),
    ]
