# Generated by Django 3.1.7 on 2021-12-10 20:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0063_lesson_lesson_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagesfromhomeworks',
            name='created_at',
        ),
        migrations.AddField(
            model_name='gallery',
            name='is_deleted',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='promo',
            name='expires',
            field=models.DateField(default=datetime.date(2021, 12, 11)),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='was',
            field=models.DateField(default='10/12/2021'),
        ),
    ]
