# Generated by Django 3.1.7 on 2021-12-15 18:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0064_auto_20211210_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesfromhomeworks',
            name='homework',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='first.gallery'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='expires',
            field=models.DateField(default=datetime.date(2021, 12, 16)),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='was',
            field=models.DateField(default='15/12/2021'),
        ),
    ]
