# Generated by Django 3.1.7 on 2021-12-20 19:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0065_auto_20211215_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='part',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='promo',
            name='expires',
            field=models.DateField(default=datetime.date(2021, 12, 21)),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='was',
            field=models.DateField(default='20/12/2021'),
        ),
        migrations.CreateModel(
            name='CourseParts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_num', models.IntegerField(default=0)),
                ('part_name', models.CharField(default=0, max_length=500)),
                ('course_num', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='first.courses')),
            ],
        ),
    ]
