# Generated by Django 3.1.7 on 2021-12-22 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0067_auto_20211220_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='image_compressed',
            field=models.ImageField(default=0, upload_to='gallery_compressed'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='expires',
            field=models.DateField(default=datetime.date(2021, 12, 23)),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='was',
            field=models.DateField(default='22/12/2021'),
        ),
    ]
